import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // showHeader: boolean;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
